# Xavier Bresson
# conda env create -f environment.yml
# conda activate deeplearn_course
# note: It took 10 min to install the environment

name: deeplearn_course
channels:
  - pypi # pip
  - conda-forge # numpy/scipy/rdkit etc
  - pytorch # DL
  - defaults
dependencies:
  # basic
  - python=3.8
  - numpy=1.24
  - jupyter=1.0
  - ipython=8.12
  - matplotlib=3.7
  - scipy=1.10.1
  - networkx=3.1
  - pip=24.2
  - pandas=2.0
  - seaborn=0.13
  # molecule
  - rdkit=2023.09.6
  # deep learning
  - pytorch=2.1.2 # DL
  - torchvision=0.16 # CV 
  - pip: # critical : a double indentation is required to install pip packages below !
    - gym==0.26 # RL


